# This is a basic workflow to help you get started with Actions

name: CI


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest


    steps:
    
      - uses: actions/checkout@v4

      
      - name: Build Image
        run:  docker build -t maxkamgang/portfolio . 

     
      - name: Push Image
        run: |
            docker login -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
            docker push maxkamgang/portfolio

            